"use client";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Dashboard.module.css";
import { motion } from "framer-motion";

export default function Dashboard() {
  function hamburger(){
    document.querySelector(".mobile").style.display = "block";
  }
  function Close(){
    document.querySelector(".mobile").style.display = "none";
  }
  function sign(){
    document.querySelector("#signup").click();
  }
  return (
    <>
      <Head>
        <title>Buycex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/buycexlogo.svg" />
        <link  rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css "/>
      </Head>
      <div id={styles.dashboar} onClick={() => {
        if(document.querySelector("#drop").style.display == "block"){
          document.querySelector("#drop").style.display = "none";
        }else{
          document.querySelector("#drop").style.display = "block";
        }
      }}>
        <Link href="/Signup" id="signup"/>
        <motion.div id={styles.mobile} style={{display: "none"}} className="mobile"
          initial={{opacity:0, x:-100}}
          whileInView={{opacity:1, x:0}}
          transition={{duration:1}}
        >
          <img src="/icon-close.svg" onClick={Close}/>
          <div>
            <Link href="#gerStarted">Buy Crypto</Link>
            <Link href="#market">Markets</Link>
            <Link href="#trade">Trades</Link>
            <Link href="#Derivates">Derivates</Link>
            <Link href="#earn">Earns</Link>
            <Link href="#Media">Media</Link>
            <Link href="#">Infinity</Link>
            <button>Deposit</button>
          </div>
        </motion.div>
        <motion.header className={styles.header}
          initial={{y: -50, opacity:0}}
          whileInView={{y:0, opacity:1}}
          transition={{duration:2}}
        >
          <img src="/buycexlogo.svg" style={{width: "100px"}}/>
          <div>
            <Link href="#gerStarted">Buy Crypto</Link>
            <Link href="#market">Markets</Link>
            <Link href="#trade">Trades</Link>
            <Link href="#Derivates">Derivates</Link>
            <Link href="#earn">Earns</Link>
            <Link href="#Media">Media</Link>
          </div>
          <div>
            <button onClick={sign}>Deposit</button>
            <aside>
              <i class="fa-solid fa-user" onClick={() => {
                document.querySelector("#drop").style.display = "block";
              }}></i>
              <div id="drop">
                <nav>
                  <div>A</div>
                  <nav>
                    <h4>ADEMOLA001</h4>
                    <p>UID:8746564737</p>
                  </nav>
                </nav>
                <div>
                  <button>Unverified</button>
                  <button>Regular User</button>
                </div>
                <h2>Assets Overview <img src="/icon-park-outline_eyes.svg" alt="" /></h2>
                <h4>0.00 <sub>USD</sub></h4>
                <p>0.000000001BTC</p>
                <li><img src="/Vector.svg" alt="" /> Home</li>
                <li><img src="/tabler_asset-filled.svg" alt="" /> Assets</li>
                <li><img src="/mdi_learn.svg" alt="" /> Earn</li>
                <li><img src="/Frame 222.svg" alt="" /> Account</li>
                <li><img src="/healthicons_referral.svg" alt="" /> Referral</li>
                <li><img src="/mdi_hub-outline.svg" alt="" /> Reward Hub</li>
                <li><img src="ant-design_setting-outlined.svg" alt="" /> Settings</li>
              </div>
              
            </aside>
            
            
            <i class="fa-solid fa-bell"></i>
          </div>
          <img src="icon-hamburger.svg" id={styles.ham} onClick={hamburger}/>
        </motion.header>
        <div>
          <nav>
            <motion.h1
              initial={{x:50, opacity:0}}
              whileInView={{opacity:1, x:0}}
              transition={{duration: 1, delay:0.2}}
            >Where the Future of Crypto Begins!</motion.h1>
            <motion.p
              initial={{x:-50, opacity:0}}
              whileInView={{opacity:1, x:0}}
              transition={{duration: 1, delay:0.2}}
            >Trade Crypto <span>Anywhere, Capture</span> Every Opportunity.</motion.p>
            <motion.button
              initial={{y:50, opacity:0}}
              whileInView={{opacity:1, y:0}}
              transition={{duration: 2, delay:0.2, type: "spring", stiffness: 120}}
            >Deposit</motion.button>
          </nav>
          <motion.img src="/herosection-img.svg"
            initial={{scale:0.3, opacity:0}}
            whileInView={{opacity:1, scale:1}}
            transition={{duration: 2, delay:0.2}}
          />
        </div>

        <aside>
          <nav id="nav">
            <img src="/image 13.svg"/>
            <div>
              <span>BCX Pre Sale</span>
              <nav>
                <p>BuyCex</p>
                <button>On Going</button>
              </nav>
            </div>
          </nav>
          <nav>
            <h4>10h  :  56 m   : 07 s</h4>
            <label>Coming soon</label>
          </nav>
          <nav>
            <button>
              <img src="/Vector.svg"/>
              Subscribed
            </button>
          </nav>
        </aside>
      </div>
    </>
  );
}
