import Head from "next/head";
import Link from "next/link";
import style from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Buycex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/buycexlogo.svg" />
      </Head>
      <div id={style.div}>
        <header className={style.header}>
          <img src="/buycexlogo.svg" style={{width: "100px"}}/>
          <div>
            <Link href="#">Buy Crypto</Link>
            <Link href="#">Markets</Link>
            <Link href="#">Trades</Link>
            <Link href="#">Derivates</Link>
            <Link href="#">Earns</Link>
            <Link href="#">Media</Link>
            <Link href="#">Infinity</Link>
          </div>
          <div>
            <img src="/solar_moon-bold-duotone.svg"/>
            <button>Sign up</button>
          </div>
          <img src="icon-hamburger.svg"/>
        </header>

        <div>
          <nav>
            <h1>Where the Future of Crypto Begins!</h1>
            <p>Trade Crypto <span>Anywhere, Capture</span> Every Opportunity.</p>
            <button>Get Started</button>
          </nav>
          <img src="/herosection-img.svg"/>
        </div>

        <aside>
          <nav id="nav">
            <img src="/image 13.svg"/>
            <div>
              <span>BCX Pre Sale</span>
              <nav>
                <p>BuyCex</p>
                <button>On Going</button>
              </nav>
            </div>
          </nav>
          <nav>
            <h4>10h  :  56 m   : 07 s</h4>
            <label>Coming soon</label>
          </nav>
          <nav>
            <button>
              <img src="/Vector.svg"/>
              Subscribed
            </button>
          </nav>
        </aside>

        <section id={style.middleSection}>
          <img src="/image1.svg"/>
          <img src="/image2.svg"/>
          <img src="/image3.svg"/>
          <img src="/image4.svg"/>
        </section>

        <h1>Crypto Market Overviews</h1>
        <article>
          <section style={{border: "2px solid gray"}}>
            <span>Hot Tokens</span>
            <div>
              <nav>
                <h4>Trading Pair</h4>
                <p><img src="/image 19.svg"/> CVM/USDT</p>
                <p><img src="/Frame 68.svg"/> BTC/USDT</p>
                <p><img src="/cryptocurrency-color_eth.svg"/> ETH/USDT</p>
                <p><img src="/token-branded_sol.svg"/> SOL/USDT</p>
                <p><img src="/cryptocurrency-color_usdc.svg"/> USDC/USDT</p>
                <p><img src="/cryptocurrency-color_bnb.svg"/> BNB/USDT</p>
              </nav>
              <nav>
                <h4>Price</h4>
                <p>$0.1</p>
                <p>$0.1</p>
                <p>$0.1</p>
                <p>$0.1</p>
                <p>$0.1</p>
                <p>$0.1</p>
              </nav>
              <nav>
                <h4>Change</h4>
                <button className={style.green}>+0.10%</button>
                <button className={style.green}>+0.10%</button>
                <button className={style.red}>+0.10%</button>
                <button className={style.green}>+0.10%</button>
                <button className={style.red}>+0.10%</button>
                <button className={style.red}>+0.10%</button>
              </nav>
              <nav>
                <h4>Trade</h4>
                <button>Trade</button>
                <button>Trade</button>
                <button>Trade</button>
                <button>Trade</button>
                <button>Trade</button>
                <button>Trade</button>
              </nav>
            </div>
          </section>
          <section className={style.main}>
            <article>
              {/* <h2>Top Gainer</h2> */}
              <nav>
                <h4>Trading Pair</h4>
                <p><img src="/image 19.svg"/> CVM/USDT</p>
                <p><img src="/Frame 68.svg"/> BTC/USDT</p>
                <p><img src="/token-branded_sol.svg"/> SOL/USDT</p>
              </nav>
              <nav>
                <h4>Price</h4>
                <p>$0.1</p>
                <p>$0.1</p>
                <p>$0.1</p>
              </nav>
              <nav>
                <h4>Change</h4>
                <button className={style.green}>+0.10%</button>
                <button className={style.green}>+0.10%</button>
                <button className={style.green}>+0.10%</button>
              </nav>
              <nav>
                <h4>Trade</h4>
                <button>Trade</button>
                <button>Trade</button>
                <button>Trade</button>
              </nav>
            </article>
            <article>
              <nav>
                <h4>Trading Pair</h4>
                <p><img src="/image 19.svg"/> CVM/USDT</p>
                <p><img src="/Frame 68.svg"/> BTC/USDT</p>
                <p><img src="/token-branded_sol.svg"/> SOL/USDT</p>
              </nav>
              <nav>
                <h4>Price</h4>
                <p>$0.1</p>
                <p>$0.1</p>
                <p>$0.1</p>
              </nav>
              <nav>
                <h4>Change</h4>
                <button className={style.red}>+0.10%</button>
                <button className={style.red}>+0.10%</button>
                <button className={style.red}>+0.10%</button>
              </nav>
              <nav>
                <h4>Trade</h4>
                <button>Trade</button>
                <button>Trade</button>
                <button>Trade</button>
              </nav>
            </article>
          </section>
        </article>

        <h1 className={style.h1}>How To Get Started</h1>

        <section>
          <aside>
            <nav>
              <span>1</span>
              <img src="/image 21 (2).svg"/>
            </nav>
            <h4>Create Account</h4>
            <p>Sign up and complete beginner tasks, win-up to $6666.</p>
            <button>Sign up now</button>
          </aside>
          <aside>
            <nav>
              <span>2</span>
              <img src="/image 21 (3).svg"/>
            </nav>
            <h4>CFund Your Account</h4>
            <p>Add funds to your account to start your crypto investment journey.</p>
            <button>Deposit/Buy now</button>
          </aside>
          <aside>
            <nav>
              <span>3</span>
              <img src="/image 21 (4).svg"/>
            </nav>
            <h4>Start Trading</h4>
            <p>Sell, buy or copy trade crypto and explore more.</p>
            <button>Trade now</button>
          </aside>
        </section>
        <h1>Discover more products</h1>

        <summary>
          <section>
            <nav>
              <h4>Spot Trade</h4>
              <p>Engage in real-time cryptocurrency trading with our intuitive platform</p>
            </nav>
            <img src="/image 22.png"/>
          </section>
          <section>
            <nav>
              <h4>Earn</h4>
              <p>Maximize your crypto holdings by earning passive income</p>
            </nav>
            <img src="/image 22 (1).png"/>
          </section>
        </summary>

        <nav>
          <h2>Secure, Ownership- Driven Crypto Exchange</h2>
        </nav>
        <div id={style.wrapper}>
          <section>
            <img src="/Frame 107 (1).svg"/>
            <h4>Secure Asset Storage </h4>
            <p>Our cutting-edge encryption and storage solutions guarantee the safety and security of your assets at all times.</p>
          </section>
          <section>
            <img src="/Frame 107 (1).svg"/>
            <h4>Secure Asset Storage </h4>
            <p>Our cutting-edge encryption and storage solutions guarantee the safety and security of your assets at all times.</p>
          </section>
          <section>
            <img src="/Frame 107 (1).svg"/>
            <h4>Secure Asset Storage </h4>
            <p>Built with a security-first approach, our platform ensures rapid detection and response to cyber threats, giving you confident control and ownership.</p>
          </section>
          <section>
            <img src="/Frame 107 (1).svg"/>
            <h4>Secure Asset Storage </h4>
            <p>Proof of Reserves (PoR) verifies BuyCex’s custody of blockchain assets, ensuring full coverage of all user funds.</p>
          </section>
        </div>

        <div className={style.wrapper}>
          <section>
            <nav>
              <h2>Keep Trading on-the Go. Anywhere, anytime</h2>
              <p>Trade across platforms on BuyCex with our app and website</p>
            </nav>
            <nav>
              <img src="/image 27.svg"/>
              <div>
                <h4>Scan QR Code</h4>
                <p>Download BuyCex app for Android/IOS</p>
                <button>App Store</button>
                <button>Android Play</button>
              </div>
            </nav>
          </section>
          <img src="/image 28.svg"/>
        </div>
        <h2>Keep Trading on-the Go. Anywhere, anytime</h2>
        <article>
          <summary>
            <h2>24/7 Customer Service</h2>
            <p>Your questions, answered. Contact BuyCex customer support with your questions at any time.</p>
            <nav>
              <button>Get Help</button>
              <img src="/image 29.svg"/>
            </nav>
          </summary>
          <summary>
            <h2>Join Our Community</h2>
            <p>The BuyCex Global Community is home to millions of users from 200+ countries, with support for 20+ languages..</p>
            <nav>
              <button>Join now</button>
              <img src="/image 30.svg"/>
            </nav>
          </summary>
        </article>

        <div className={style.containers}>
          <h1>FAQ</h1>
          <div>
            <p>1. What is Bitcoin?</p>
            <img src="mingcute_plus-fill.svg"/>
          </div>
          <div>
            <p>2. How do I buy Bitcoin?</p>
            <img src="mingcute_plus-fill.svg"/>
          </div>
          <div>
            <p>3. Is cryptocurrency secure?</p>
            <img src="mingcute_plus-fill.svg"/>
          </div>
          <div>
            <p>4. What is blockchain?</p>
            <img src="mingcute_plus-fill.svg"/>
          </div>
        </div>
        <div className={style.content}>
          <h2>Start Your Crypto Journey Now!</h2>
          <button>Sign Up Now</button>
        </div>

        <footer>
          <section>
            <h4>Corporate</h4>
            <p>About us</p>
            <p>Join In</p>
            <p>Blog</p>
            <p>News and announcement</p>
            <p>Official Verification Center</p>
            <p>PoR (Proof of reverse)</p>
            <p>Term of Use </p>
            <p>Privacy Policy</p>
            <p>Risk Disclosure Statement </p>
            <p>AML & CFE </p>
            <p>Cookies Reference</p>
          </section>
          <section>
            <h4>Services</h4>
            <p>About us</p>
            <p>Join In</p>
            <p>Blog</p>
            <p>News and announcement</p>
            <p>Official Verification Center</p>
            <p>PoR (Proof of reverse)</p>
            <p>Term of Use </p>
            <p>Privacy Policy</p>
            <p>Risk Disclosure Statement </p>
            <p>AML & CFE </p>
            <p>Cookies Reference</p>
          </section>
          <section>
            <h4>Services</h4>
            <p>About us</p>
            <p>Join In</p>
            <p>Blog</p>
            <p>News and announcement</p>
            <p>Official Verification Center</p>
            <p>PoR (Proof of reverse)</p>
            <p>Term of Use </p>
            <p>Privacy Policy</p>
            <p>Risk Disclosure Statement </p>
            <p>AML & CFE </p>
            <p>Cookies Reference</p>
          </section>
          <section>
            <h4>Learns</h4>
            <p>About us</p>
            <p>Join In</p>
            <p>Blog</p>
            <p>News and announcement</p>
            <p>Official Verification Center</p>
            <p>PoR (Proof of reverse)</p>
            <p>Term of Use </p>
            <p>Privacy Policy</p>
            <p>Risk Disclosure Statement </p>
            <p>AML & CFE </p>
            <p>Cookies Reference</p>
          </section>
          <section>
            <h4>Products</h4>
            <p>About us</p>
            <p>Join In</p>
            <p>Blog</p>
            <p>News and announcement</p>
            <p>Official Verification Center</p>
            <p>PoR (Proof of reverse)</p>
            <p>Term of Use </p>
            <p>Privacy Policy</p>
            <p>Risk Disclosure Statement </p>
            <p>AML & CFE </p>
            <p>Cookies Reference</p>
          </section>
        </footer>
        <li>Designed by Abdulmalik(codeWithFaith)</li>
      </div>
    </>
  );
}
