"use client";
import Head from "next/head";
import Link from "next/link";
import style from "../styles/Home.module.css";
import { motion } from "framer-motion";

export default function Home() {
  function hamburger(){
    document.querySelector(".mobile").style.display = "block";
  }
  function Close(){
    document.querySelector(".mobile").style.display = "none";
  }
  function sign(){
    document.querySelector("#signup").click();
  }
  return (
    <>
      <Head>
        <title>Buycex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/buycexlogo.svg" />
      </Head>
      <div id={style.div}>
        <Link href="/Signup" id="signup"/>
        <motion.div id={style.mobile} style={{display: "none"}} className="mobile"
          initial={{opacity:0, x:-100}}
          whileInView={{opacity:1, x:0}}
          transition={{duration:1}}
        >
          <img src="/icon-close.svg" onClick={Close}/>
          <div>
            <Link href="#gerStarted">Buy Crypto</Link>
            <Link href="#market">Markets</Link>
            <Link href="#trade">Trades</Link>
            <Link href="#Derivates">Derivates</Link>
            <Link href="#earn">Earns</Link>
            <Link href="#Media">Media</Link>
            <Link href="#">Infinity</Link>
            <button>Sign up</button>
          </div>
        </motion.div>
        <motion.header className={style.header}
          initial={{y: -50, opacity:0}}
          whileInView={{y:0, opacity:1}}
          transition={{duration:2}}
        >
          <img src="/buycexlogo.svg" style={{width: "100px"}}/>
          <div>
            <Link href="#gerStarted">Buy Crypto</Link>
            <Link href="#market">Markets</Link>
            <Link href="#trade">Trades</Link>
            <Link href="#Derivates">Derivates</Link>
            <Link href="#earn">Earns</Link>
            <Link href="#Media">Media</Link>
            <Link href="#">Infinity</Link>
          </div>
          <div>
            <button onClick={sign}>Sign up</button>
          </div>
          <img src="icon-hamburger.svg" id={style.ham} onClick={hamburger}/>
        </motion.header>

        
        <div>
          <nav>
            <motion.h1
              initial={{x:50, opacity:0}}
              whileInView={{opacity:1, x:0}}
              transition={{duration: 1, delay:0.2}}
            >Where the Future of Crypto Begins!</motion.h1>
            <motion.p
              initial={{x:-50, opacity:0}}
              whileInView={{opacity:1, x:0}}
              transition={{duration: 1, delay:0.2}}
            >Trade Crypto <span>Anywhere, Capture</span> Every Opportunity.</motion.p>
            <motion.button
              initial={{y:50, opacity:0}}
              whileInView={{opacity:1, y:0}}
              transition={{duration: 2, delay:0.2, type: "spring", stiffness: 120}}
            >Get Started</motion.button>
          </nav>
          <motion.img src="/herosection-img.svg"
            initial={{scale:0.3, opacity:0}}
            whileInView={{opacity:1, scale:1}}
            transition={{duration: 2, delay:0.2}}
          />
        </div>

        <aside>
          <nav id="nav">
            <img src="/image 13.svg"/>
            <div>
              <span>BCX Pre Sale</span>
              <nav>
                <p>BuyCex</p>
                <button>On Going</button>
              </nav>
            </div>
          </nav>
          <nav>
            <h4>10h  :  56 m   : 07 s</h4>
            <label>Coming soon</label>
          </nav>
          <nav>
            <button>
              <img src="/Vector.svg"/>
              Subscribed
            </button>
          </nav>
        </aside>

        <section id={style.middleSection}>
          <motion.img src="/image1.svg"
            initial={{opacity:0, scale:0.8}}
            whileInView={{opacity:1, scale:1}}
            transition={{duration:1}}
          />
          <motion.img src="/image2.svg"
            initial={{opacity:0, scale:0.8}}
            whileInView={{opacity:1, scale:1}}
            transition={{duration:1, delay:0.3}}
          />
          <motion.img src="/image3.svg"
            initial={{opacity:0, scale:0.8}}
            whileInView={{opacity:1, scale:1}}
            transition={{duration:1, delay:0.6}}
          />
          <motion.img src="/image4.svg"
            initial={{opacity:0, scale:0.8}}
            whileInView={{opacity:1, scale:1}}
            transition={{duration:1, delay:0.8}}
          />
        </section>

        <h1 id="market">Crypto Market Overviews</h1>
        <article>
          <motion.section style={{border: "2px solid gray"}}
            initial={{opacity:0, y:100}}
            whileInView={{opacity:1, y:0}}
            transition={{duration:2}}
          >
            <span>Hot Tokens</span>
            <div>
              <nav>
                <h4>Trading Pair</h4>
                <p><img src="/image 19.svg"/> CVM/USDT</p>
                <p><img src="/Frame 68.svg"/> BTC/USDT</p>
                <p><img src="/cryptocurrency-color_eth.svg"/> ETH/USDT</p>
                <p><img src="/token-branded_sol.svg"/> SOL/USDT</p>
                <p><img src="/cryptocurrency-color_usdc.svg"/> USDC/USDT</p>
                <p><img src="/cryptocurrency-color_bnb.svg"/> BNB/USDT</p>
              </nav>
              <nav>
                <h4>Price</h4>
                <p>$0.1</p>
                <p>$0.1</p>
                <p>$0.1</p>
                <p>$0.1</p>
                <p>$0.1</p>
                <p>$0.1</p>
              </nav>
              <nav>
                <h4>Change</h4>
                <button className={style.green}>+0.10%</button>
                <button className={style.green}>+0.10%</button>
                <button className={style.red}>+0.10%</button>
                <button className={style.green}>+0.10%</button>
                <button className={style.red}>+0.10%</button>
                <button className={style.red}>+0.10%</button>
              </nav>
              <nav>
                <h4>Trade</h4>
                <button>Trade</button>
                <button>Trade</button>
                <button>Trade</button>
                <button>Trade</button>
                <button>Trade</button>
                <button>Trade</button>
              </nav>
            </div>
          </motion.section>
          <section className={style.main}>
            <motion.article
              initial={{opacity:0, y:-100}}
              whileInView={{opacity:1, y:0}}
              transition={{duration:2}}
            >
              <nav>
                <h4>Trading Pair</h4>
                <p><img src="/image 19.svg"/> CVM/USDT</p>
                <p><img src="/Frame 68.svg"/> BTC/USDT</p>
                <p><img src="/token-branded_sol.svg"/> SOL/USDT</p>
              </nav>
              <nav>
                <h4>Price</h4>
                <p>$0.1</p>
                <p>$0.1</p>
                <p>$0.1</p>
              </nav>
              <nav>
                <h4>Change</h4>
                <button className={style.green}>+0.10%</button>
                <button className={style.green}>+0.10%</button>
                <button className={style.green}>+0.10%</button>
              </nav>
              <nav>
                <h4>Trade</h4>
                <button>Trade</button>
                <button>Trade</button>
                <button>Trade</button>
              </nav>
            </motion.article>
            <motion.article
              initial={{opacity:0, y:100}}
              whileInView={{opacity:1, y:0}}
              transition={{duration:2}}
            >
              <nav>
                <h4>Trading Pair</h4>
                <p><img src="/image 19.svg"/> CVM/USDT</p>
                <p><img src="/Frame 68.svg"/> BTC/USDT</p>
                <p><img src="/token-branded_sol.svg"/> SOL/USDT</p>
              </nav>
              <nav>
                <h4>Price</h4>
                <p>$0.1</p>
                <p>$0.1</p>
                <p>$0.1</p>
              </nav>
              <nav>
                <h4>Change</h4>
                <button className={style.red}>+0.10%</button>
                <button className={style.red}>+0.10%</button>
                <button className={style.red}>+0.10%</button>
              </nav>
              <nav>
                <h4>Trade</h4>
                <button>Trade</button>
                <button>Trade</button>
                <button>Trade</button>
              </nav>
            </motion.article>
          </section>
        </article>

        <motion.h1 id="gerStarted" className={style.h1}
          initial={{opacity:0, y:100}}
            whileInView={{opacity:1, y:0}}
            transition={{duration:2}}
        >How To Get Started</motion.h1>

        <section>
          <motion.aside
            initial={{opacity:0, y:100}}
            whileInView={{opacity:1, y:0}}
            transition={{duration:2}}
          >
            <nav>
              <span>1</span>
              <img src="/image 21 (2).svg"/>
            </nav>
            <h4>Create Account</h4>
            <p>Sign up and complete beginner tasks, win-up to $6666.</p>
            <button>Sign up now</button>
          </motion.aside>
          <motion.aside
            initial={{opacity:0, y:100}}
            whileInView={{opacity:1, y:0}}
            transition={{duration:2, delay:0.2}}
          >
            <nav>
              <span>2</span>
              <img src="/image 21 (3).svg"/>
            </nav>
            <h4>CFund Your Account</h4>
            <p>Add funds to your account to start your crypto investment journey.</p>
            <button>Deposit/Buy now</button>
          </motion.aside>
          <motion.aside
            initial={{opacity:0, y:100}}
            whileInView={{opacity:1, y:0}}
            transition={{duration:2, delay:0.4}}
          >
            <nav>
              <span>3</span>
              <img src="/image 21 (4).svg"/>
            </nav>
            <h4>Start Trading</h4>
            <p>Sell, buy or copy trade crypto and explore more.</p>
            <button>Trade now</button>
          </motion.aside>
        </section>
        <h1>Discover more products</h1>

        <summary>
          <motion.section
            initial={{opacity:0, x:-100}}
            whileInView={{opacity:1, x:0}}
            transition={{duration:2}}
          >
            <nav>
              <h4>Spot Trade</h4>
              <p>Engage in real-time cryptocurrency trading with our intuitive platform</p>
            </nav>
            <img src="/image 22.png"/>
          </motion.section>
          <motion.section
            initial={{opacity:0, x:100}}
            whileInView={{opacity:1, x:0}}
            transition={{duration:2}}
          >
            <nav>
              <h4>Earn</h4>
              <p>Maximize your crypto holdings by earning passive income</p>
            </nav>
            <img src="/image 22 (1).png"/>
          </motion.section>
        </summary>

        <nav id="Derivates">
          <h2>Secure, Ownership- Driven Crypto Exchange</h2>
        </nav>
        <div id={style.wrapper}>
          <motion.section
            initial={{opacity:0, y:100}}
            whileInView={{opacity:1, y:0}}
            transition={{duration:2}}
          >
            <img src="/Frame 107 (1).svg"/>
            <h4>Secure Asset Storage </h4>
            <p>Our cutting-edge encryption and storage solutions guarantee the safety and security of your assets at all times.</p>
          </motion.section>
          <motion.section
            initial={{opacity:0, y:100}}
            whileInView={{opacity:1, y:0}}
            transition={{duration:2, delay:0.3}}
          >
            <img src="/Frame 107 (1).svg"/>
            <h4>Secure Asset Storage </h4>
            <p>Our cutting-edge encryption and storage solutions guarantee the safety and security of your assets at all times.</p>
          </motion.section>
          <motion.section
            initial={{opacity:0, y:-100}}
            whileInView={{opacity:1, y:0}}
            transition={{duration:2}}
          >
            <img src="/Frame 107 (1).svg"/>
            <h4>Secure Asset Storage </h4>
            <p>Built with a security-first approach, our platform ensures rapid detection and response to cyber threats, giving you confident control and ownership.</p>
          </motion.section>
          <motion.section
            initial={{opacity:0, y:100}}
            whileInView={{opacity:1, y:0}}
            transition={{duration:2}}
          >
            <img src="/Frame 107 (1).svg"/>
            <h4>Secure Asset Storage </h4>
            <p>Proof of Reserves (PoR) verifies BuyCex’s custody of blockchain assets, ensuring full coverage of all user funds.</p>
          </motion.section>
        </div>

        <div id="trade" className={style.wrapper}>
          <section>
            <nav>
              <h2>Keep Trading on-the Go. Anywhere, anytime</h2>
              <p>Trade across platforms on BuyCex with our app and website</p>
            </nav>
            <nav>
              <img src="/image 27.svg"/>
              <div>
                <h4>Scan QR Code</h4>
                <p>Download BuyCex app for Android/IOS</p>
                <button>App Store</button>
                <button>Android Play</button>
              </div>
            </nav>
          </section>
          <img src="/image 28.svg"/>
        </div>
        <h2 id="earn">Keep Trading on-the Go. Anywhere, anytime</h2>
        <article>
          <motion.summary
            initial={{opacity:0, x:-100}}
            whileInView={{opacity:1, x:0}}
            transition={{duration:1, delay:0.2}}
          >
            <h2>24/7 Customer Service</h2>
            <p>Your questions, answered. Contact BuyCex customer support with your questions at any time.</p>
            <nav>
              <button>Get Help</button>
              <img src="/image 29.svg"/>
            </nav>
          </motion.summary>
          <motion.summary
            initial={{opacity:0, x:100}}
            whileInView={{opacity:1, x:0}}
            transition={{duration:1, delay:0.3}}
          >
            <h2>Join Our Community</h2>
            <p>The BuyCex Global Community is home to millions of users from 200+ countries, with support for 20+ languages..</p>
            <nav>
              <button>Join now</button>
              <img src="/image 30.svg"/>
            </nav>
          </motion.summary>
        </article>

        <div className={style.containers}>
          <h1>FAQ</h1>
          <div>
            <p>1. What is Bitcoin?</p>
            <img src="mingcute_plus-fill.svg"/>
          </div>
          <div>
            <p>2. How do I buy Bitcoin?</p>
            <img src="mingcute_plus-fill.svg"/>
          </div>
          <div>
            <p>3. Is cryptocurrency secure?</p>
            <img src="mingcute_plus-fill.svg"/>
          </div>
          <div>
            <p>4. What is blockchain?</p>
            <img src="mingcute_plus-fill.svg"/>
          </div>
        </div>
        <div className={style.content}>
          <motion.h2
            initial={{opacity:0, y:100}}
            whileInView={{opacity:1, y:0}}
            transition={{duration:1}}
          >Start Your Crypto Journey Now!</motion.h2>
          <motion.button
            initial={{opacity:0, x:-100}}
            whileInView={{opacity:1, x:0}}
            transition={{duration:5, type: "spring", stiffness: 150}}
          >Sign Up Now</motion.button>
        </div>

        <footer id="Media">
          <motion.section
            initial={{opacity:0}}
            whileInView={{opacity:1}}
            transition={{duration:2}}
          >
            <h4>Corporate</h4>
            <p>About us</p>
            <p>Join In</p>
            <p>Blog</p>
            <p>News and announcement</p>
            <p>Official Verification Center</p>
            <p>PoR (Proof of reverse)</p>
            <p>Term of Use </p>
            <p>Privacy Policy</p>
            <p>Risk Disclosure Statement </p>
            <p>AML & CFE </p>
            <p>Cookies Reference</p>
          </motion.section>
          <motion.section
            initial={{opacity:0}}
            whileInView={{opacity:1}}
            transition={{duration:2, delay:0.2}}
          >
            <h4>Services</h4>
            <p>About us</p>
            <p>Join In</p>
            <p>Blog</p>
            <p>News and announcement</p>
            <p>Official Verification Center</p>
            <p>PoR (Proof of reverse)</p>
            <p>Term of Use </p>
            <p>Privacy Policy</p>
            <p>Risk Disclosure Statement </p>
            <p>AML & CFE </p>
            <p>Cookies Reference</p>
          </motion.section>
          <motion.section
            initial={{opacity:0}}
            whileInView={{opacity:1}}
            transition={{duration:2, delay:0.4}}
          >
            <h4>Services</h4>
            <p>About us</p>
            <p>Join In</p>
            <p>Blog</p>
            <p>News and announcement</p>
            <p>Official Verification Center</p>
            <p>PoR (Proof of reverse)</p>
            <p>Term of Use </p>
            <p>Privacy Policy</p>
            <p>Risk Disclosure Statement </p>
            <p>AML & CFE </p>
            <p>Cookies Reference</p>
          </motion.section>
          <motion.section
            initial={{opacity:0}}
            whileInView={{opacity:1}}
            transition={{duration:2, delay:0.6}}
          >
            <h4>Learns</h4>
            <p>About us</p>
            <p>Join In</p>
            <p>Blog</p>
            <p>News and announcement</p>
            <p>Official Verification Center</p>
            <p>PoR (Proof of reverse)</p>
            <p>Term of Use </p>
            <p>Privacy Policy</p>
            <p>Risk Disclosure Statement </p>
            <p>AML & CFE </p>
            <p>Cookies Reference</p>
          </motion.section>
          <motion.section
            initial={{opacity:0}}
            whileInView={{opacity:1}}
            transition={{duration:2, delay:1}}
          >
            <h4>Products</h4>
            <p>About us</p>
            <p>Join In</p>
            <p>Blog</p>
            <p>News and announcement</p>
            <p>Official Verification Center</p>
            <p>PoR (Proof of reverse)</p>
            <p>Term of Use </p>
            <p>Privacy Policy</p>
            <p>Risk Disclosure Statement </p>
            <p>AML & CFE </p>
            <p>Cookies Reference</p>
          </motion.section>
        </footer>
        <li>Designed by Abdulmalik(codeWithFaith)</li>
      </div>
    </>
  );
}
